apiVersion: v1
kind: Template
labels:
  app: ${APP_NAME}
  app: prometheus
message: Template for postgresql db who need scrape metrics from pods monitoring
metadata:
  annotation:
    openshift.io/path: metrics
    openshift.io/port: 9187

  name: postgres-persistent
objects:
- kind: ImageStream
  metadata: 
    labels:
      app: ${APPLICATION_NAME}
- kind: Service
  apiVersion: v1
  metadata:
    label:
      app: ${APPLICATION_NAME}

- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    label:
      app: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    containers:
    - name: postgres
      env:
       - name: POSTGRESQL_DATABASE
         value: ${PGSQL_DB}
       - name: POSTGRESQL_USER
         value: ${PGSQL_USER}
       - name: POSTGRESQL_PASSWORD
         value: ${PGSQL_PASSWORD}
      image: centos/postgresql-96-centos7:latest
      volumeMounts:
      - name: pg-data-volume
        mountPath: /var/lib/pgsql/data
    - name: sidecar
      env:
        - name: DATA_SOURCE_NAME
          value: "postgresql://${POSTGRESQL_USER}:${POSTGRESQL_PASSWORD}@localhost:5432/${POSTGRESQL_DATABASE}?sslmode=disable"
      image: wrouesnel/postgres_exporter
    volumes:
    - name: pg-data-volume
      persistentVolumeClaim:
        claimName: postgres-data
parameters:
- description: The name of instance of Application
  displayName: Application name in openshift project
  name: APPLICATION_NAME
  required: true 
  value: postgresql-db-01

- description: Postgresql user name for connection to database 
  displayName: Postgresql username
  name: PGSQL_USER
  required: true
  value: admin

- description: Postgresql password for connection to database 
  displayName: Postgresql password
  name: PGSQL_PASSWORD
  required: true
  value: admin

- description: Postgresql database name  
  displayName: Postgresql database
  name: PGSQL_DB
  required: true
  value: db01

